### PR TITLE
360 bug   several client components arent using the getuser hook

### LINKED ISSUE #360: [BUG] - several client components aren't using the getUser hook
## Describe the bug

Due to the fact that several places aren't using the getUser hook, it spams requests to our Supabase.

## Expected behavior

Each client request should be switched to the hook from #99

### PR DESCRIPTION
**Pull request by Aradon267**
## Description

This PR handles cases where unusual ways of getting a user's ID were used, and where things were faulty with the getUser hook.

Fixes #360 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

All calls worked as expected

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: cv_next/app/actions/users/getUser.ts [hunk 1]
```diff
@@ -16,13 +16,10 @@ import Definitions from "@/lib/definitions";
...
- * Retrieves user data by user ID.
- *
- * @param {string} userId - The ID of the user to retrieve
- * @return {Promise<Result<UserModel, string>>} A promise that resolves to a Result containing the user data or an error message
+ * Retrieves a specific user's data by it's name.
+ * @param {string} username - The username of the user to retrieve
+ * @returns {Promise<Result<UserModel, string>>} A promise that resolves to a Result containing the user data or an error message
  */
-//TODO: delete this and replace any user-related fetches with getUser(),
-// currently this relies on user id received from the browser which is unsafe.
```
Comment (YechiamW3) [inline cv_next/app/actions/users/getUser.ts:25]: is this no longer a relevant comment? why? (I don't see it addressed in the pr)

File: cv_next/hooks/useUser.ts [hunk 2]
```diff
@@ -55,7 +67,7 @@ export const useUser = () => {
     data: userIsAdmin,
     mutate: mutateAdmin,
     error: adminError,
-  } = useSWR(data?.id ? "user_admin" : null, getUserAdminStatus, {
+  } = useSWR("user_admin", getUserAdminStatus, {
```
Comment (YechiamW3) [inline cv_next/hooks/useUser.ts:70]: constant hardcode usage

File: cv_next/app/actions/users/getUser.ts (hunk 1 above)
Comment (Aradon267) [reply cv_next/app/actions/users/getUser.ts:25]: Technically you are correct, all API calls are still based on the user id and the username is used mainly for the url to the profile.
I'll return the comment.

File: cv_next/hooks/useUser.ts (hunk 2 above)
Comment (Aradon267) [reply cv_next/hooks/useUser.ts:70]: What's the difference between this and the "user" that there's several lines above it? This isn't some field from Supabase
