### PR TITLE
FIXED: cogwheel not checking author ID against real user ID

### LINKED ISSUE #385: [BUG] - <Cogwheel refreshes page>
## Describe the bug

When pressing the cogwheel for more options when editing my uploaded CV - the components refresh themselves and the menu collapses, making me unable to edit my uploaded files.

## To Reproduce

1. Go to uploads
2. Click on cogwheel 
3. See error

## Expected behavior

A menu opens, letting me interact and change my uploaded file.

## Environment

- **OS:** [iOS 18.6.1]
- **Browser:** [Safari]
  **Version:**

## Additional context
Screen recording of the issue:

https://github.com/user-attachments/assets/a825eca7-3e00-4189-9c40-62e74b59e1a8

### PR DESCRIPTION
**Pull request by Aradon267**
## Description

Updated the CV modification permission check to check against the deconstructed CV author ID

Fixes #385 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Using:
Admin on his own CV and another user's CV (both worked)
Regular user on his own CV and another user's CV (only first worked)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### CODE REVIEW

File: cv_next/app/actions/cvs/checkPermission.ts [hunk 1]
```diff
@@ -20,8 +20,15 @@ export async function checkCVModifyPermission(
     );
   }
 
+  // Note that in a different PR, there's a function that extracts it more easily
```
Comment (YechiamW3) [inline cv_next/app/actions/cvs/checkPermission.ts]: Wait so why not merge that PR and use it, that'd just be a duplication we get in the final code

Comment (Aradon267) [reply cv_next/app/actions/cvs/checkPermission.ts]: I think that it's a part of an unmerged pr that has a bit more work on it
Currently not near my pc to be sure, but maybe I can put it in this PR and then use what I'll add here in the other?

Comment (YechiamW3) [reply cv_next/app/actions/cvs/checkPermission.ts]: Whichever you prefer; the point is to have it unified. If you'd prefer to merge this pr first then change the other one (also mention it by # here so we'll have the connection).
(also delete the code comment afterwards)

Comment (Aradon267) [reply cv_next/app/actions/cvs/checkPermission.ts]: done
